name: Sounds Only Pack Conversion
description: Request an automated conversion for sound files only
title: "[Sounds Only]: "
labels: ["sounds-only"]
body:
  - type: markdown
    attributes:
      value: |
        Please be sure to include a directly downloadable link to your pack. The action will fail if the pack cannot be downloaded.

  - type: input
    id: java-pack-url
    attributes:
      label: Java Pack Direct Download URL
      description: Please provide a direct link to the Java Edition resource pack to be converted.
      placeholder: e.g. https://example.com/my_resource_pack.zip
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Cupjok/java2bedrock-sounds/blob/main/CODE_OF_CONDUCT.md)
        You further agree that you either own or have permission to use any content you have linked to within this form.
      options:
        - label: I agree to follow this project's Code of Conduct and I have permission to use all assets I have linked to within this form.
          required: true
